### ISSUE TITLE
extra closed beckets are getting generated

### ISSUE THREAD

**Issue by rsheshadri239912** [mesejo/trex#10] opened 2023-07-11 15:24 UTC
Hello Developer,

Below is the query sent and it is generating extra ")".

**code:**
import trrex as tx
tx.make(['IBS(.*|)TECH','IBS(.|)SOL','IBS(.*|)TEHK'], prefix=r"\b(", suffix=r")")

**output='\\b(IBS(.(?:|)SOL|*|)TE(?:HK|CH)))'**

Please let me know if any further information is required on the same.

Thanks,
Rangam

**Comment by rsheshadri239912** [comment] 2023-07-11 16:19
![image](https://github.com/mesejo/trex/assets/87691690/46a84158-b00e-409e-893c-e840bef71e46)

This is the only error I getting but your package is doing excellent work and saving a lot of looping time.

**Comment by mesejo** [comment] 2023-07-11 16:30
Thanks for the positive feedback, I cannot reproduce the problem with version 0.0.5 (master branch). Did you install it via pip?

**Comment by mesejo** [comment] 2023-07-11 16:47
I was able to reproduce the error but using the branch `new-ideas`. Did you install the library doing `pip install trrex`?

**Comment by mesejo** [comment] 2023-07-26 17:10
Closing as I cannot reproduce and the error seems to be fixed

**Closed by mesejo** 2023-07-26 17:10 UTC
